# Generated by Django 4.1.3 on 2023-06-17 21:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='document',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='client',
            name='global_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='client',
            name='type',
            field=models.CharField(choices=[('CC', 'CC'), ('CE', 'CE'), ('TI', 'TI'), ('PPT', 'PPT'), ('PASAPORTE', 'PASAPORTE')], default='CC', max_length=10, verbose_name='Tipo documento'),
        ),
        migrations.AddField(
            model_name='pet',
            name='allergies',
            field=models.CharField(default='Desconocido', max_length=100, verbose_name='alergias'),
        ),
        migrations.AddField(
            model_name='pet',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='pet',
            name='color',
            field=models.CharField(default='Desconocido', max_length=50, verbose_name='color'),
        ),
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.CharField(default='Desconocido', max_length=10, verbose_name='sexo'),
        ),
        migrations.AddField(
            model_name='pet',
            name='race',
            field=models.CharField(default='Desconocido', max_length=50, verbose_name='raza'),
        ),
        migrations.AddField(
            model_name='pet',
            name='reproductive_status',
            field=models.CharField(default='Desconocido', max_length=50, verbose_name='estado reproductivo'),
        ),
        migrations.AddField(
            model_name='pet',
            name='temper',
            field=models.CharField(default='Desconocido', max_length=50, verbose_name='temperamento'),
        ),
        migrations.AddField(
            model_name='pet',
            name='veterinary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='veterinary.veterinary'),
        ),
        migrations.AddField(
            model_name='pet',
            name='weight',
            field=models.CharField(default='Desconocido', max_length=20, verbose_name='peso'),
        ),
        migrations.AddField(
            model_name='user',
            name='has_seen_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='veterinary',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='veterinary',
            name='password',
            field=models.CharField(default='admin', max_length=128),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='veterinary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='veterinary.veterinary'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.IntegerField(default='Desconocido', verbose_name='edad'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets', to='veterinary.client'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='namePet',
            field=models.CharField(max_length=50, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='especie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='veterinary',
            name='cityVeterinary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='veterinary',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='veterinary',
            name='nameVeterinary',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='veterinary',
            name='nit',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('document', 'email', 'veterinary')},
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CL', 'Clínica'), ('GU', 'Guardería'), ('PE', 'Peluquería')], max_length=20, verbose_name='tipo_servicio')),
                ('start', models.DateTimeField(verbose_name='fecha_inicio')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='fecha_final')),
                ('details', models.TextField(blank=True, null=True, verbose_name='observaciones')),
                ('state', models.CharField(choices=[('Activo', 'Activo'), ('Finalizado', 'Finalizado')], default='Activo', max_length=10, verbose_name='Estado')),
                ('total_time', models.IntegerField(blank=True, null=True, verbose_name='Tiempo')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='veterinary.pet')),
                ('veterinary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='veterinary.veterinary')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(default=datetime.datetime.now)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinary.client')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('pvp', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio de venta')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinary.category', verbose_name='Categoría')),
                ('veterinary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='veterinary.veterinary')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Consulta', max_length=255, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('start', models.DateTimeField(default=datetime.datetime.now)),
                ('room', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'is_doctor': True}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='veterinary.pet')),
                ('veterinary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='veterinary.veterinary')),
            ],
        ),
        migrations.CreateModel(
            name='DetSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('cant', models.IntegerField(default=0)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinary.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinary.sale')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalle de Ventas',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='veterinary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='veterinary.veterinary'),
        ),
        migrations.RemoveField(
            model_name='client',
            name='mobil',
        ),
    ]
