# Generated by Django 4.1.3 on 2022-11-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinary',
            name='password',
            field=models.CharField(default='admin', max_length=50),
        ),
    ]
