# Generated by Django 4.1.3 on 2023-06-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0002_category_client_document_client_global_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='room',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.IntegerField(default='Desconocido', verbose_name='edad'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='allergies',
            field=models.CharField(default='Desconocido', max_length=100, verbose_name='alergias'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='color',
            field=models.CharField(default='Desconocido', max_length=50, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(default='Desconocido', max_length=10, verbose_name='sexo'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='namePet',
            field=models.CharField(max_length=50, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='race',
            field=models.CharField(default='Desconocido', max_length=50, verbose_name='raza'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='reproductive_status',
            field=models.CharField(default='Desconocido', max_length=50, verbose_name='estado reproductivo'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='especie'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='temper',
            field=models.CharField(default='Desconocido', max_length=50, verbose_name='temperamento'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.CharField(default='Desconocido', max_length=20, verbose_name='peso'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock'),
        ),
        migrations.AlterField(
            model_name='services',
            name='total_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Tiempo'),
        ),
        migrations.AlterField(
            model_name='services',
            name='type',
            field=models.CharField(choices=[('CL', 'Clínica'), ('GU', 'Guardería'), ('PE', 'Peluquería')], max_length=20, verbose_name='tipo_servicio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='veterinary',
            name='cityVeterinary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='veterinary',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='veterinary',
            name='nameVeterinary',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='veterinary',
            name='nit',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='veterinary',
            name='password',
            field=models.CharField(default='admin', max_length=128),
        ),
    ]
