# Generated by Django 4.1.3 on 2022-11-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0003_alter_user_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinary',
            name='direccion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
