# Generated by Django 4.1.3 on 2022-11-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0004_veterinary_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='identification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
