# Generated by Django 4.1.3 on 2022-11-04 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0005_client_identification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='mobil',
        ),
    ]
