# Generated by Django 4.1.3 on 2022-11-05 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0006_remove_client_mobil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='veterinary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='veterinary.veterinary'),
        ),
        migrations.AlterField(
            model_name='veterinary',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='veterinary',
            name='nameVeterinary',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='veterinary',
            name='nit',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
