# Generated by Django 4.1.3 on 2022-11-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0008_alter_veterinary_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
