# Generated by Django 4.1.3 on 2022-11-20 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0010_remove_pet_age_pet_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='veterinary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='veterinary.veterinary'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='veterinary.client'),
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('room', models.CharField(max_length=15)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='veterinary.client')),
                ('especialista', models.ForeignKey(limit_choices_to={'is_doctor': True}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='veterinary.pet')),
            ],
        ),
    ]
