# Generated by Django 4.1.3 on 2022-11-20 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0011_user_is_doctor_alter_client_veterinary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date',
            old_name='especialista',
            new_name='doctor',
        ),
    ]
