# Generated by Django 4.1.3 on 2022-11-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0012_rename_especialista_date_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
