# Generated by Django 4.1.3 on 2022-11-20 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0013_date_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='hour',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(),
        ),
    ]
