# Generated by Django 4.1.3 on 2022-11-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0016_date_hour_alter_date_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(default='2022-11-22'),
        ),
    ]
