# Generated by Django 4.1.3 on 2022-11-27 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0018_events_alter_date_date_alter_date_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='veterinary.client'),
        ),
        migrations.AddField(
            model_name='events',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'is_doctor': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='events',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='events',
            name='pet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='veterinary.pet'),
        ),
        migrations.AddField(
            model_name='events',
            name='room',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='name',
            field=models.CharField(blank=True, default=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='veterinary.pet'), max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='start',
            field=models.DateTimeField(blank=True, default=models.DateTimeField(blank=True, null=True), null=True),
        ),
    ]
