# Generated by Django 4.1.3 on 2022-11-27 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0019_events_client_events_doctor_events_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='veterinary.client'),
        ),
        migrations.AlterField(
            model_name='events',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'is_doctor': True}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='events',
            name='name',
            field=models.CharField(blank=True, default=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='veterinary.pet'), max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='veterinary.pet'),
        ),
        migrations.AlterField(
            model_name='events',
            name='room',
            field=models.CharField(max_length=15),
        ),
    ]
