# Generated by Django 4.1.3 on 2022-11-27 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0021_alter_events_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Date',
        ),
    ]
