# Generated by Django 4.1.3 on 2023-02-16 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinary', '0023_category_sale_product_detsale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='client',
        ),
        migrations.AlterField(
            model_name='events',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
