# Generated by Django 4.1.2 on 2023-03-02 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("veterinary", "0024_remove_events_client_alter_events_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/%Y/%m/%d", verbose_name="Imagen"
            ),
        ),
    ]
