# Generated by Django 4.1.2 on 2023-03-03 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("veterinary", "0026_remove_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
