# Generated by Django 4.1.2 on 2023-03-03 23:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("veterinary", "0027_alter_client_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="document",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="global_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="client",
            unique_together={("document", "email", "veterinary")},
        ),
        migrations.RemoveField(
            model_name="client",
            name="identification",
        ),
    ]
