# Generated by Django 4.1.2 on 2023-03-03 23:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "veterinary",
            "0028_client_document_client_global_id_alter_client_email_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="global_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
