# Generated by Django 4.1.7 on 2023-03-07 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("veterinary", "0029_alter_client_global_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="detsale",
            options={},
        ),
        migrations.AlterModelOptions(
            name="sale",
            options={},
        ),
        migrations.RemoveField(
            model_name="detsale",
            name="cant",
        ),
        migrations.RemoveField(
            model_name="detsale",
            name="prod",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="iva",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="subtotal",
        ),
        migrations.AddField(
            model_name="detsale",
            name="iva",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="detsale",
            name="product",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="details",
                to="veterinary.product",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="detsale",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sale",
            name="created_by",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="detsale",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="detsale",
            name="sale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="veterinary.sale",
            ),
        ),
        migrations.AlterField(
            model_name="detsale",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="sale",
            name="client",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="veterinary.client",
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
