# Generated by Django 4.1.7 on 2023-03-08 10:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("veterinary", "0030_alter_detsale_options_alter_sale_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="detsale",
            options={
                "ordering": ["id"],
                "verbose_name": "Detalle de Venta",
                "verbose_name_plural": "Detalle de Ventas",
            },
        ),
        migrations.AlterModelOptions(
            name="sale",
            options={
                "ordering": ["id"],
                "verbose_name": "Venta",
                "verbose_name_plural": "Ventas",
            },
        ),
        migrations.RemoveField(
            model_name="detsale",
            name="iva",
        ),
        migrations.RemoveField(
            model_name="detsale",
            name="product",
        ),
        migrations.RemoveField(
            model_name="detsale",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="client",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="created_date",
        ),
        migrations.AddField(
            model_name="detsale",
            name="cant",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="detsale",
            name="prod",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="veterinary.product",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sale",
            name="cli",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="veterinary.client",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sale",
            name="date_joined",
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="sale",
            name="iva",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name="sale",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name="detsale",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name="detsale",
            name="sale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="veterinary.sale"
            ),
        ),
        migrations.AlterField(
            model_name="detsale",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name="sale",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
