# Generated by Django 4.1.7 on 2023-03-14 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("veterinary", "0031_alter_detsale_options_alter_sale_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="date_joined",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
