# Generated by Django 4.1.7 on 2023-03-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("veterinary", "0032_alter_sale_date_joined"),
    ]

    operations = [
        migrations.AddField(
            model_name="detsale",
            name="iva",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
