# Generated by Django 4.1.7 on 2023-03-21 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("veterinary", "0033_detsale_iva"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="estado",
            field=models.CharField(
                choices=[
                    ("CL", "Clínica"),
                    ("GU", "Guardería"),
                    ("PE", "Peluquería"),
                    ("NO", "Normal"),
                ],
                default="NO",
                max_length=2,
                verbose_name="estado",
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="birthdate",
            field=models.DateField(
                blank=True, null=True, verbose_name="fecha de nacimiento"
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pets",
                to="veterinary.client",
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="gender",
            field=models.CharField(
                default="Desconocido", max_length=6, verbose_name="género"
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="namePet",
            field=models.CharField(max_length=30, verbose_name="nombre"),
        ),
        migrations.AlterField(
            model_name="pet",
            name="species",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="especie"
            ),
        ),
    ]
