# Generated by Django 4.1.7 on 2023-03-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("veterinary", "0034_pet_estado_alter_pet_birthdate_alter_pet_client_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Cliente"),
        ),
    ]
