# Generated by Django 4.1.7 on 2023-03-21 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("veterinary", "0035_alter_client_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CL", "Clínica"),
                            ("GU", "Guardería"),
                            ("PE", "Peluquería"),
                        ],
                        max_length=2,
                        verbose_name="tipo_servicio",
                    ),
                ),
                ("start", models.DateTimeField(verbose_name="fecha_inicio")),
                (
                    "end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha_final"
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True, null=True, verbose_name="observaciones"
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servicios",
                        to="veterinary.pet",
                    ),
                ),
            ],
        ),
    ]
