# Generated by Django 4.1.7 on 2023-03-21 17:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("veterinary", "0037_rename_servicio_services"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pet",
            name="estado",
        ),
    ]
