# Generated by Django 4.1.7 on 2023-03-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("veterinary", "0039_services_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="total_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Tiempo"),
        ),
    ]
